### ISSUE TITLE
How to handle updates and other message types

### ISSUE THREAD

**Issue by cunninghamb505** [microsoft/FHIR-Converter#207]
When ADT is flowing inbound how do you match encounters. Example: A01 is sent that creates an encounter record in FHIR. An A03 is sent for the patient discharge. Does Azure  know to update the correct encounter ID  or does it create a new encounter ID record? If I were to search via FHIR for that patients encounters, would I see one response or two? 

So far I created a another template for A03’s, but I see two encounters after sending the A03. How would this work for updates and other transaction types. I am assuming we would have to query the “lastupdated” value in resource to filter?
Thank you,
Brandon

**Comment by BoyaWu10** [comment]
When generating FHIR resources, each FHIR resource has its own ID generation template. For example, [this](https://github.com/microsoft/FHIR-Converter/blob/main/data/Templates/Hl7v2/ID/_Encounter.liquid) is an ID generation template for Encounter, where the converter tries to fetch PV1.19.1 and PV1.19.4 as the input to compute the ID for Encounter. If these two components are not available, the converter uses the whole PV1.19. So no matter where the Encounter is generated (ADT A01 or A03), if they have the same PV1.19.1 and PV1.19.4, or the same PV1.19, they will have the same ID. Otherwise different IDs are generated. If current ID generation logic does not meet your scenario, you can update the ID generation template or create your own ones.

**Comment by cunninghamb505** [comment]
Thank you,
Is that only for the lucid template. looks like I am still using the handlebars version. Do you recommend moving to lucid setup

**Comment by ranvijaykumar** [comment]
Yes, that logic is available only in Liquid templates. We recommend moving to Liquid if you want to use that feature.

**Comment by cunninghamb505** [comment]
Ahh that makes sense. Ok i will start moving that change. Can I simply point my current injestHL7 to the ACR for liquid templates. Or do i have to rebuild the injest platform to re configure? 
Thank you,
Brandon

**Comment by ranvijaykumar** [comment]
You will need to reconfigure your pipeline. The Liquid engine can be used either as a command line tool, or the $convert-data operation in the FHIR server. See the documentation: Azure API for FHIR: https://docs.microsoft.com/en-us/azure/healthcare-apis/convert-data FHIR Server for Azure: https://github.com/microsoft/fhir-server/blob/main/docs/ConvertDataOperation.md

**Comment by cunninghamb505** [comment]
Ok I ran the deployment script but it doesn't ask anywhere about connecting my current ingest to the liquid template. How do I connect my mllp to https connector to route correctly to the liquid converter, instead of the handlebars app? I think those instructions are missing somewhere. When I call $convert-data it only converts it, its not adding the bundle to the server.
