### ISSUE TITLE
HL7v2 to FHIR conversion default CodeSystem rules not working

### ISSUE THREAD

**Issue by ranvijaykumar** [microsoft/FHIR-Converter#241]
Ref: https://stackoverflow.com/questions/67376307/hl7v2-to-fhir-conversion-default-codesystem-rules-not-working

**Comment by jchen76** [comment]
The fix is not working. After I add the codes in /CodeSystem/CodeSystem.json as instructed, I got "Conversion Error - Process failed: The code system mapping file is invalid". If I remove the default setting, the error is gone.
![add default language](https://user-images.githubusercontent.com/28128065/118040331-03027d00-b337-11eb-808c-74680e24fd71.jpg)
![code mapping file is invalid error](https://user-images.githubusercontent.com/28128065/118040347-08f85e00-b337-11eb-864d-28b52e7e26f1.jpg)

**Comment by ranvijaykumar** [comment]
It seems you are missing the closing bracket for the __default__ node.
Try this:
"CodeSystem/Language": {
            "__default__": {
                "code" : "English",
                "display" : "English",
                "system" : "English"
            }                
        }

**Comment by jchen76** [comment]
It's working. Thanks.
