### ISSUE TITLE
Missing reference to appointment on encounter resources generated by SIU S12

### ISSUE THREAD

**Issue by aart-janboor** [microsoft/FHIR-Converter#340]
The Encounter resources generated by parsing SIU S12 (appointment) messages are missing a reference to the appointment that created the encounter. As per the documentation (http://hl7.org/fhir/encounter.html)  appointment is an optional field. We store tasks related to the appointment on the related encounter object and hence need to establish the link between the encounter resource and the appointment that created it. Also - when the appointment is rescheduled or changed this impacts the encounter and accordingly it's useful to couple the two.

**Comment by ginalee-dotcom** [comment]
Hi @aart-janboor, thank you for pointing this out. In our SIU_S12 template, Encounter gets created from PV1 segment, which is an optional segment. Therefore, there can be a missing reference to the Appointment resource if PV1 is missing - which is okay, as the appointment is an optional field as you have mentioned. In addition, there can be scenarios in which we don't need the link in the first place. For example, if the status of the Encounter resource is 'planned', then ideally there shouldn't be a reference to an Appointment' resource since the Encounter has not technically occurred yet. If needed, you can always add in additional mappings by modifying our existing conversion template for SIU_S12.
